import CustomProvider from './components/customProvider';
import Footer from './components/layout/footer';
import Header from './components/layout/header';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='text-white'>
        <CustomProvider>
          <Header />
          {children}
          <Footer />
        </CustomProvider>
      </body>
    </html>
  );
}
